Chore: Test

diff --git a/.github/workflows/main-release-webapi.yml b/.github/workflows/main-release-webapi.yml
--- a/.github/workflows/main-release-webapi.yml
+++ b/.github/workflows/main-release-webapi.yml
@@ -10,37 +10,37 @@ on:
       - main
   
 jobs:
-  container-test:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+  # container-test:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
 
-      - name: Build and Run Docker Compose for Healthcheck Test
-        run: |
-          docker compose -f ./prod/docker-compose.yml up nginx -d
-          sleep 15
+  #     - name: Build and Run Docker Compose for Healthcheck Test
+  #       run: |
+  #         docker compose -f ./prod/docker-compose.yml up nginx -d
+  #         sleep 15
 
-      - name: Test Healthcheck Endpoint
-        run: |
-          for i in {1..20}; do
-            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9999/healthz)
-            if [ "$STATUS" -eq 200 ]; then
-              echo "Healthcheck passed with status $STATUS"
-              exit 0
-            else
-              echo "Healthcheck attempt $i failed with status $STATUS. Retrying..."
-              sleep 2
-            fi
-          done
-          echo "Healthcheck failed after 20 attempts."
-          exit 1
+  #     - name: Test Healthcheck Endpoint
+  #       run: |
+  #         for i in {1..20}; do
+  #           STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9999/healthz)
+  #           if [ "$STATUS" -eq 200 ]; then
+  #             echo "Healthcheck passed with status $STATUS"
+  #             exit 0
+  #           else
+  #             echo "Healthcheck attempt $i failed with status $STATUS. Retrying..."
+  #             sleep 2
+  #           fi
+  #         done
+  #         echo "Healthcheck failed after 20 attempts."
+  #         exit 1
 
   load-test:
     runs-on: ubuntu-latest
-    needs: container-test
+    # needs: container-test
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
